import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import DataViewer from "./components/DataViewer";
/* import imgData from "../public/clock.svg";
import Image from "next/image"; */

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className = "principal">
      <DataViewer  />
      </main>
      {/*  <div style={{ padding: "5%" }} className="main-size">
        <Image src={imgData} alt="Img" style={{ width: 200 }} />
        <DataViewer  />
      </div> */}

      <footer className={styles.footer}>
        <strong> Powered by </strong>
        <div> Luis Miguel Zacarias</div>
      </footer>
    </div>
  );
}
